version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: filemanager-server
    ports:
      - "8001:8001"
    volumes:
      - ./images:/images
      - ./nginx.conf:/etc/nginx/nginx.conf
